import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ErrorWrapper } from "./error-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-yellow-600 p-4">
          <p className="text-center text-black text-2xl font-bold">Header</p>
        </header>
        <ErrorWrapper>{children}</ErrorWrapper>
        <footer className="bg-yellow-600 p-4 w-full">
          <p className="text-center text-black text-2xl font-bold">Footer</p>
        </footer>
      </body>
    </html>
  );
}